name: sdk
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  cli_table: ^1.0.2
  http: ^1.6.0
  path: ^1.9.0
  win32_registry: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
